name: IMavatar
channels:
  - pytorch3d
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.2.1=h06a4308_0
  - certifi=2021.10.8=py37h06a4308_2
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.11.0=h70c0345_0
  - fvcore=0.1.5.post20210804=pyhd8ed1ab_0
  - giflib=5.2.1=h7b6447c_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=pyhd8ed1ab_0
  - jpeg=9d=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=py37hd09550d_3
  - numpy=1.21.2=py37h20f2e39_0
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=py37_0
  - openssl=1.1.1m=h7f8727e_0
  - pillow=9.0.1=py37h22f2fdc_0
  - pip=21.2.2=py37h06a4308_0
  - portalocker=2.3.0=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.7.0=py3.7_cuda11.0.221_cudnn8.0.3_0
  - pytorch3d=0.6.1=py37_cu110_pyt170
  - pyyaml=6.0=py37h7f8727e_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.37.2=hc218d9a_0
  - tabulate=0.8.9=py37h06a4308_0
  - termcolor=1.1.0=py37h06a4308_1
  - tk=8.6.11=h1ccaba5_0
  - torchvision=0.8.0=py37_cu110
  - tqdm=4.62.3=pyhd3eb1b0_1
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=pyhd3eb1b0_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.9
    - chumpy==0.70
    - click==8.0.3
    - configparser==5.2.0
    - cycler==0.11.0
    - cython==0.29.20
    - dataclasses==0.6
    - dill==0.3.4
    - dlib==19.22.1
    - docker-pycreds==0.4.0
    - fonttools==4.28.5
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - gputil==1.4.0
    - grpcio==1.43.0
    - hydra-core==1.0.6
    - idna==3.3
    - imageio==2.13.5
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.10.0
    - importlib-resources==5.4.0
    - imutils==0.5.4
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - multidict==5.2.0
    - networkx==2.6.3
    - oauthlib==3.1.1
    - omegaconf==2.0.6
    - opencv-python==4.5.2.54
    - packaging==21.3
    - pathtools==0.1.2
    - plotly==5.5.0
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.0
    - pyhocon==0.3.59
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytorch-lightning==1.3.3
    - pywavelets==1.2.0
    - requests==2.27.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - rtree==0.9.7
    - scikit-image==0.19.1
    - scipy==1.7.3
    - sentry-sdk==1.5.1
    - shortuuid==1.0.8
    - smmap==5.0.0
    - subprocess32==3.5.4
    - tenacity==8.0.1
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tifffile==2021.11.2
    - torchmetrics==0.6.2
    - trimesh==3.9.39
    - urllib3==1.26.7
    - usd-core==20.11
    - wandb==0.12.9
    - werkzeug==2.0.2
    - yarl==1.7.2
    - yaspin==2.1.0
    - zipp==3.7.0
    - pygit2==1.9.1
